helmCharts:
  - releaseName: self-hosted-basic
    namespace: arc-runners
    name: gha-runner-scale-set-0.9.3
    valuesInline:
      githubConfigUrl: https://github.com/senacor-playground
      githubConfigSecret: github-runners-app
      template:
        spec:
          containers:
            - name: runner
              image: europe-docker.pkg.dev/senacor-playground/beppo-repo/actions-runner-with-tool-cache:latest
              command: ["/home/runner/run.sh"]
              resources:
                requests:
                  cpu: 1000m
                  memory: 2.0Gi
              env:
                - name: DISABLE_RUNNER_UPDATE
                  value: "true"
      controllerServiceAccount:
        namespace: arc-systems
        name: arc-gha-rs-controller
      minRunners: 1
resources:
  - secret.yaml
