apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: external-secrets
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  sourceType: helm
  helm:
    repo: oci://europe-docker.pkg.dev/senacor-playground/beppo-repo/imported/helm/external-secrets
    chart: external-secrets
    version: 0.9.13
    releaseName: external-secrets
    namespace: external-secrets
    auth: k8sserviceaccount
    values:
      image:
        repository: europe-docker.pkg.dev/senacor-playground/beppo-repo/imported/ghcr.io/external-secrets/external-secrets
      certController:
        image:
          repository: europe-docker.pkg.dev/senacor-playground/beppo-repo/imported/ghcr.io/external-secrets/external-secrets
      webhook:
        image:
          repository: europe-docker.pkg.dev/senacor-playground/beppo-repo/imported/ghcr.io/external-secrets/external-secrets
      serviceAccount:
        annotations:
          iam.gke.io/gcp-service-account: {{.Values.externalSecretsServiceAccountEmail}}
