apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-runner-app
  namespace: arc-systems
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  dataFrom:
    - extract:
        key: github-runner-app
