apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-store
spec:
  provider:
    gcpsm:
      projectID: $SECRET_PROJECT_ID
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test
  namespace: external-secrets
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  data:
    - secretKey: test
      remoteRef:
        key: test
