helmCharts:
  - releaseName: external-secrets
    namespace: external-secrets
    name: external-secrets
    valuesInline:
      image:
        repository: europe-docker.pkg.dev/senacor-playground/beppo-repo/imported/ghcr.io/external-secrets/external-secrets
      certController:
        image:
          repository: europe-docker.pkg.dev/senacor-playground/beppo-repo/imported/ghcr.io/external-secrets/external-secrets
      webhook:
        image:
          repository: europe-docker.pkg.dev/senacor-playground/beppo-repo/imported/ghcr.io/external-secrets/external-secrets
      serviceAccount:
        annotations:
          iam.gke.io/gcp-service-account: $EXTERNAL_SECRETS_SERVICE_ACCOUNT_EMAIL
resources:
  - cluster-secret-store.yaml
