name: Build Image

on:
  push:
    branches: [main]

permissions:
  contents: "read"
  id-token: "write"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/211935152727/locations/global/workloadIdentityPools/github/providers/senacor-playground
      - uses: google-github-actions/setup-gcloud@v2
      - run: gcloud auth configure-docker europe-docker.pkg.dev
      - name: Build and push image
        working-directory: ${{ runner.tool_cache }}
        run: |
          folder_paths=("node/16.20.2" "node/20.11.1")

          echo "FROM europe-docker.pkg.dev/senacor-playground/beppo-repo/imported/ghcr.io/actions/actions-runner:2.314.1" > Dockerfile
          for folder_path in ${folder_paths[@]}; do
            echo "COPY $folder_path /home/runner/_work/_tool/$folder_path" >> Dockerfile
          done

          cat Dockerfile

          buildah build --layers --timestamp 0 -t "$IMAGE" .
          buildah push "$IMAGE"
        env:
          IMAGE: europe-docker.pkg.dev/senacor-playground/beppo-repo/actions-runner-with-tool-cache:latest
