name: Build Image

on:
  push:
    branches: [main]

permissions:
  contents: "read"
  id-token: "write"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      INPUT_IMAGE: europe-docker.pkg.dev/senacor-playground/beppo-repo/imported/ghcr.io/actions/actions-runner:2.314.1
      OUTPUT_IMAGE: europe-docker.pkg.dev/senacor-playground/beppo-repo/actions-runner-with-tool-cache:buildx
    steps:
      - name: Clear existing tool cache
        run: rm -rf ${{ runner.tool_cache }}/*

      # -----------------------------------------------------------------------
      # Install tools
      # -----------------------------------------------------------------------
      - uses: google-github-actions/setup-gcloud@v2
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      # -----------------------------------------------------------------------
      # End: Install tools
      # -----------------------------------------------------------------------

      - name: Create Dockerfile
        working-directory: ${{ runner.tool_cache }}
        run: |
          echo "FROM $INPUT_IMAGE" > Dockerfile
          while IFS= read -r -d '' folder_path; do
            echo "COPY --chown=1001:1001 $folder_path /home/runner/_work/_tool/$folder_path" >> Dockerfile
          done < <(find . -mindepth 2 -maxdepth 2 -type d -print0)
          echo "⚙️ Generated Dockerfile:"
          cat Dockerfile

          echo "**/__pycache__" > .dockerignore
          echo "⚙️ Generated .dockerignore:"
          cat .dockerignore
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/211935152727/locations/global/workloadIdentityPools/github/providers/senacor-playground
      - uses: google-github-actions/setup-gcloud@v2
      - run: gcloud auth configure-docker europe-docker.pkg.dev
      - name: Build image # Using Buildah due to its support for reproducible builds
        working-directory: ${{ runner.tool_cache }}
        run: buildah build --layers --timestamp 0 -t "$OUTPUT_IMAGE" .
      - name: Push image
        run: buildah push "$OUTPUT_IMAGE"
