name: Build Image

on:
  push:
    branches: [main]

permissions:
  contents: "read"
  id-token: "write"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install buildah
      - run: |
          newcontainer=$(buildah from ghcr.io/actions/actions-runner:2.314.1)
          buildah add $newcontainer "${{ runner.tool_cache }}node/20.11.1" "/home/runner/_work/_tool/node/20.11.1"
      # - name: Prepare Dockerfile
      #   run: |
      #     echo "FROM ghcr.io/actions/actions-runner:2.314.1" > Dockerfile
      #     echo "COPY --from=tool-cache node/20.11.1 /home/runner/_work/_tool/node/20.11.1/" >> Dockerfile
      #     cat Dockerfile
      # - name: Docker build
      #   run: docker build --no-cache --build-context "tool-cache=${{ runner.tool_cache }}" . -t europe-docker.pkg.dev/senacor-playground/beppo-repo/actions-runner-with-tool-cache:latest
      #   env:
      #     DOCKER_BUILDKIT: 1
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/211935152727/locations/global/workloadIdentityPools/github/providers/senacor-playground
      - uses: google-github-actions/setup-gcloud@v2
      - run: gcloud auth configure-docker europe-docker.pkg.dev
      # - run: docker push europe-docker.pkg.dev/senacor-playground/beppo-repo/actions-runner-with-tool-cache:latest
      - run: buildah commit $newcontainer europe-docker.pkg.dev/senacor-playground/beppo-repo/actions-runner-with-tool-cache:latest
