name: Build Image

on:
  push:
    branches: [main]

permissions:
  contents: "read"
  id-token: "write"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build image
        run: |
          docker run -id --name my_container ghcr.io/actions/actions-runner:2.314.1
          docker cp "${{ runner.tool_cache }}/node/16.20.2" "my_container:/home/runner/_work/_tool/node/16.20.2"
          docker cp "${{ runner.tool_cache }}/node/20.11.1" "my_container:/home/runner/_work/_tool/node/20.11.1"
          docker commit my_container "$IMAGE"
          docker push "$IMAGE"

      # - name: Prepare Dockerfile
      #   run: |
      #     echo "FROM ghcr.io/actions/actions-runner:2.314.1" > Dockerfile
      #     echo "RUN mkdir -p /home/runner/_work/_tool/node/16.20.2 && cp -r /mnt/tool-cache/node/16.20.2 /home/runner/_work/_tool/node/16.20.2 && find /home/runner/_work/_tool/node/16.20.2 -exec touch {} \;" >> Dockerfile
      #     echo "RUN mkdir -p /home/runner/_work/_tool/node/20.11.1 && cp -r /mnt/tool-cache/node/20.11.1 /home/runner/_work/_tool/node/20.11.1 && find /home/runner/_work/_tool/node/20.11.1 -exec touch {} \;" >> Dockerfile
      #     echo "RUN mkdir -p /home/runner/_work/_tool/CodeQL/2.16.4 && cp -r /mnt/tool-cache/CodeQL/2.16.4 /home/runner/_work/_tool/CodeQL/2.16.4 && find /home/runner/_work/_tool/CodeQL/2.16.4 -exec touch {} \;" >> Dockerfile
      #     cat Dockerfile
      # - uses: google-github-actions/auth@v2
      #   with:
      #     workload_identity_provider: projects/211935152727/locations/global/workloadIdentityPools/github/providers/senacor-playground
      # - uses: google-github-actions/setup-gcloud@v2
      # - run: gcloud auth configure-docker europe-docker.pkg.dev
      # - name: Build image
      #   run: |
      #     sudo apt-get install buildah
      #     buildah build --layers -v "${{ runner.tool_cache }}:/mnt/tool-cache" -t "$IMAGE" .
      #     buildah push "$IMAGE"
      #   env:
      #     IMAGE: europe-docker.pkg.dev/senacor-playground/beppo-repo/actions-runner-with-tool-cache:latest
