name: Build Image

on:
  push:
    branches: [main]

permissions:
  contents: "read"
  id-token: "write"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          rm -rf /opt/hostedtoolcache/CodeQL
          rm -rf /opt/hostedtoolcache/PyPy
          rm -rf /opt/hostedtoolcache/Python
          rm -rf /opt/hostedtoolcache/Ruby
          rm -rf /opt/hostedtoolcache/go
          find "${{ runner.tool_cache }}" -type f -exec touch -t 197001010000.00 {} +
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/211935152727/locations/global/workloadIdentityPools/github/providers/senacor-playground
      - uses: google-github-actions/setup-gcloud@v2
      - run: gcloud auth configure-docker europe-docker.pkg.dev
      - name: Create Dockerfile
        run: |
          #!/bin/bash

          folder_paths=("node/16.20.2" "node/20.11.1")

          echo "FROM europe-docker.pkg.dev/senacor-playground/beppo-repo/imported/ghcr.io/actions/actions-runner:2.314.1" > Dockerfile
          for folder_path in ${folder_paths[@]}; do
            echo "Handling $folder_path"
            tarfile_name="${folder_path//\//_}.tar"
            tar -cf "$tarfile_name" "${{ runner.tool_cache }}/$folder_path" --sort=name --mtime="@0" --pax-option=exthdr.name=%d/PaxHeaders/%f,delete=atime,delete=ctime
            touch -t 197001010000.00 "$tarfile_name"
            echo "sha256: $(shasum -a 256 $tarfile_name)"
            echo "COPY $tarfile_name ." >> Dockerfile
          done

          cat Dockerfile
          ls -la
      - run: |
          sudo apt-get install buildah
          buildah build --layers --timestamp 0 -t "$IMAGE" .
          buildah push "$IMAGE"
      # - run: |
      #     docker buildx create --use --driver-opt image=moby/buildkit:v0.13.1
      #     docker buildx build --platform linux/amd64 --build-arg SOURCE_DATE_EPOCH="0" --output type=image,name=$IMAGE,push=true,rewrite-timestamp=true .
      #   env:
      #     IMAGE: europe-docker.pkg.dev/senacor-playground/beppo-repo/actions-runner-with-tool-cache:latest
