name: Build Image

on:
  push:
    branches: [main]

permissions:
  contents: "read"
  id-token: "write"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Dockerfile
        run: |
          echo "FROM ghcr.io/actions/actions-runner:2.314.1" > Dockerfile
          echo "RUN mkdir -p /home/runner/_work/_tool/node/20.11.1 && cp -r /mnt/tool-cache/node/20.11.1 /home/runner/_work/_tool/node/20.11.1 && find /home/runner/_work/_tool/node/20.11.1 -exec touch {} \;" >> Dockerfile
          cat Dockerfile
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/211935152727/locations/global/workloadIdentityPools/github/providers/senacor-playground
      - uses: google-github-actions/setup-gcloud@v2
      - run: gcloud auth configure-docker europe-docker.pkg.dev
      - name: Build image
        run: |
          sudo apt-get install buildah
          buildah build --layers --timestamp 0 -v "${{ runner.tool_cache }}:/mnt/tool-cache" -t "$IMAGE" .
          buildah push "$IMAGE"
        env:
          IMAGE: europe-docker.pkg.dev/senacor-playground/beppo-repo/actions-runner-with-tool-cache:latest
